import numpy as np

MATRIX_HEIGHT: int = ...
MATRIX_WIDTH: int = ...

class PyTetrisEngine:
    def __new__(cls, seed: int, config_json: str) -> PyTetrisEngine: ...
    def step(self, action: int) -> tuple[np.ndarray, float, int, bool, bool]: ...
    def step_bitwise(self, action: int) -> tuple[np.ndarray, float, int, bool, bool]: ...
    def current_state(self) -> np.ndarray: ...
    def current_state_bitwise(self) -> np.ndarray: ...
    def preview_fall_location(self) -> np.ndarray: ...
    def reset(self): ...
    def lines(self) -> int: ...
    def score(self) -> int: ...
    def print(self): ...
    def current_piece(self) -> str: ...
    def next_piece(self) -> str: ...