import numpy as np

MATRIX_HEIGHT: int = ...
MATRIX_WIDTH: int = ...

class PyTetrisEngine:
    def __new__(cls, seed: int, config_json: str) -> PyTetrisEngine: ...
    def step(self, action: int) -> tuple[np.ndarray, float, int, bool, bool]: ...